name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: thomashoneyman/setup-purescript@main

      - name: Build the project
        run: spago build

      - name: Run tests
        run: spago test
